name = "short-urls"
main = "src/index.js"
compatibility_date = "2024-01-01"

# [[kv_namespaces]]
# binding = "SHORT_URLS"
# id = "short-urls-namespace"
# preview_id = "short-urls-namespace-preview"

[vars]
DEFAULT_REDIRECT_TYPE = "302"
FALLBACK_URL = "/"
